### ISSUE TITLE
Tiered Release Schedule

### ISSUE THREAD

**Issue by emil2k** [dominictarr/feedopensource#14]
I really like the idea but I had few questions and a possible suggestion.

Once the iteration is funded, does the work proceed by an individual ( or small group ) then once complete the money is split up amongst them as agreed upon on beforehand? What if others want to join in to help the iteration will they get a cut? If so who determines, how much?

I ask this because if you are only going to have a small group contributing to the iteration, it may make more sense to make a closed/private branch for each iteration and incentivize the funders with a delayed release schedule, for example :

$1,000 - constant access, participation in development process, immediate release.
$100 - 2 weeks wait
$10 - 4 weeks wait
free - 8 weeks wait

Tell me what you think and if you need help, I can contribute code.

**Comment by dominictarr** [comment]
Yeah, I'd envision work being done by a small team.
It's up to them to decide how the money is divided.

Tiered Release: Hmm, this something like this _could_ create more incentive to participate.
I think this would work best for a application, rather than a tool.

I think the thing with open source is that developers _do_ pay for it, but with their time,
so I'd probably not want to create any barrier for developers, since they might find a problem and fix something.

However, I do think this is a good suggestion, and may be worthwhile experimenting with when we get to that stage.

Thanks for the offer of contributing code! please come and find me #stackvm (on freenode) and we can chat
