### ISSUE TITLE
How to pace iterations

### ISSUE THREAD

**Issue by Raynos** [dominictarr/feedopensource#28]
You have raised funding for iteration 1 and are now working on said iteration.

Given that you've funded iteration 1 and are working on it, when do you plan to start funding for iteration 2.

Whats the recommended feedopensource workflow for others?

Should they work on an iteration for some weeks and start fund raising for the next iteration at the end of the current iteration or should they start fund raising the next iteration in parallel with working on the current iteration?

**Comment by dominictarr** [comment]
I'm not finished yet - I have a new badge that shows the progress state better, getting it up shortly.

**Comment by Raynos** [comment]
@dominictarr your right, your still working on iteration 1 :) I changed the wording of the question to be better.

**Comment by dominictarr** [comment]
Ah, so I want feedopensource to be flexible, so we can figure that out together.

generally, the pattern that I have found my self in with large scale open source projects like npmd is a block of intensive work, then publish that, then users tell me about the problems, and we figure out what to do next.
1. get ideas of what to do next (sitting about thinking, posting issues etc)
2. do them (code code code)
3. get feedback on problems (more issues) GOTO 1.

step `2` is the hard work bit. 1,3 is a slower pace especially because you need to wait for people, who may be the other side of the world, to get back to you about things.
I forsee intensive bouts of programming punctuated by much more relaxed periods of discussion.
quite likely it would be possible to run two feedopensource projects interspersed, or use the quiet time for experimenting.

**Comment by Raynos** [comment]
@dominictarr that sounds like a good plan, I like it!

**Comment by dominictarr** [comment]
closing, because issue list is getting noisy.
