### ISSUE TITLE
put the iteration name / title in the badge ?

### ISSUE THREAD

**Issue by Raynos** [dominictarr/feedopensource#33]
You can't tell which iteration https://feedopensource.com/iteration/dominictarr/feedopensource/1PTAwipYpP63uNrcxfm5FewxRdZyar6ceu.png#1.2 or https://feedopensource.com/iteration/dominictarr/feedopensource/18oBEV9hFdDMEct9Ys2bSAuEY4bi2KSMHi.png#1.2 is.

Maybe it should mention the name of the issue "Iteration 1" and "Iteration 2" in the badge ?

**Comment by dominictarr** [comment]
good idea. where should the name go?
at the moment all the badge real estate is taken.

**Comment by ralphtheninja** [comment]
The name could go at the top and perhaps we could reduce the number of states it has now (created, funding, progress, complete) OR if that is not an option we could illustrate the four states graphically, rather than in text, like a traffic light with red, orange and green dots or something like that.

**Comment by dominictarr** [comment]
hmm, yeah, or have overlapping tabs that stacked so you got an impression that stuff has happened.

**Comment by Raynos** [comment]
I'm not much of a design person, I just like the idea of cramming all the information I want into a single thing I can look at. But maybe just make the image taller and put it above the created / funded / progress / completed :D

**Comment by dominictarr** [comment]
of course! brillant. it can be any size we want!

can have the path to the repo & user name too.

**Comment by joates** [comment]
> it can be any size we want

while _technically_ that is true, you probably should pick a size from the [IAB Standards](http://en.wikipedia.org/wiki/Web_banner#Standard_sizes) so that if in future people need to display a badge in a sidebar, as a tweet attachment or somewhere else on a webpage (i.e. not on github) it will just fit because it conforms to some expected standard.

Just something else to consider.. 

but of course this also leads into other "design" type issues, like should there be more than 1 badge option, maybe too early to "bring in" a designer to the discussion, although if there were a designer present they would probably be throwing stuff at me for saying that and yelling "it's never too early to think about design" (you know how they are :-P hahaha).

At this early stage at least i'd favor a single badge but with dimensions consistent with what is expected / standard / normal (i tend to prefer media at the 16:9 aspect ratio, but that's only because my screen has that ratio so bit of an edge-case there :D, the [golden ratio](http://www.radovleugel.com/golden-ratio-calculator) is equally appropriate) or just go with **mRec** which is 300x250px from the IAB standards (mRec == medium rectangle).

**Comment by dominictarr** [comment]
sounds reasonable.

**Comment by dominictarr** [comment]
okay, I've put the title in the badge, and removed the list of states - so now it only shows the current state.

**Comment by dominictarr** [comment]
the nearest size to change to would be 300x100 (currently it's 300x60) but since the canvas code is still pretty procedural that change is a bit more involved, so I think that should wait untill we actually want to put a badge in a sidebar.

**Comment by dominictarr** [comment]
iteration name is now in the badge, so closing this.
